<a href="https://colab.research.google.com/github/Anshika91/15Days_Learning/blob/main/Tensorflow_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
a= torch.tensor([[1,2,3],[4,5,6]])

In [3]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [4]:
b=torch.tensor([[10,11,12],[13,14,15]])

In [5]:
b

tensor([[10, 11, 12],
        [13, 14, 15]])

In [6]:
a+b

tensor([[11, 13, 15],
        [17, 19, 21]])

In [7]:
torch.cuda.is_available()

True

In [9]:
c=a.to("cuda:0")

In [10]:
c

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')

In [12]:
import tensorflow as tf
t= tf.constant([[1.,2.,3.],[4.,5.,6.]])

In [13]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])


In [14]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [15]:
v.assign(2 * v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>